import 'package:flutter/material.dart';
const KConstColor=Color(0xFFFFC12F);
const KConstColor2=Color(0xFFFFE6AC);
const KProductName="productName";
const KProductPrice="productPrice";
const KProductDescription="productDescription";
const KProductCaTegory="productCaTegory";
const KProductLocation="productLocation";
const KProductsCollection="products";
